// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsopyhtyvhdsergrcgdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzb3B5aHR5dmhkc2VyZ3JjZ2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NjM1MjAsImV4cCI6MjA3MTMzOTUyMH0.Bwox6VcjUXdZsG-hlmScK0LHxjMMsii9iQ8g2K5CrQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});